version: "3.5"
services:
  app:
    image: mvochoa/gomon:1.2.0-golang1.13-alpine3.10-genstructgolang0.0.4
    working_dir: /go/src/gitlab.com/melp/api
    env_file: melp.local.env
    volumes:
      - ./:/go/src/gitlab.com/melp/api
      - ./assets:/var/api/assets
      - ./cmd.sh:/usr/local/bin/cmd.sh:rw
      - go_cache:/var/api/.cache/go-build
      - go_path:/go
      - melp_storage:/var/api/storage
      - melp_tmp:/var/api/tmp
    networks:
      net_melp:
    secrets:
      - melp_passwd
      - u_read
      - u_write
    ports:
      - 3000:3000
    command: sh -c '/usr/local/bin/cmd.sh'

networks:
  net_melp:
    external: true

secrets:
  melp_passwd:
    file: melp_passwd.secret
  u_read:
    file: u_read.secret
  u_write:
    file: u_write.secret

volumes:
  melp_tmp:
  melp_storage:
  go_cache:
  go_path:
