version: "3.5"
services:
  postgres:
    image: "${CI_REGISTRY}/${CI_PROJECT_PATH_DATABASE}:test"
    env_file: melp.local.env
    secrets:
      - melp_passwd
      - u_read
      - u_write
  app:
    image: mvochoa/gomon:1.11-alpine3.8
    working_dir: /go/src/gitlab.com/gitlab.com/melp/api
    env_file: melp.local.env
    volumes:
      - ./:/go/src/gitlab.com/gitlab.com/melp/api
      - ./assets:/var/api/assets
      - melp_storage:/var/api/storage
      - melp_tmp:/var/api/tmp
    depends_on:
      - postgres
    links:
      - postgres
    secrets:
      - melp_passwd
      - u_read
      - u_write
    command: sh -c 'tail -f /dev/null'

volumes:
  melp_storage:
  melp_tmp:

secrets:
  melp_passwd:
    file: melp_passwd.secret
  u_read:
    file: u_read.secret
  u_write:
    file: u_write.secret
